'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {
      return queryInterface.bulkInsert('Zodiacs', [{
        sign_name: "Aries",
        element: "fire",
        modality: "cardinal",
        symbol: "the ram",
        dates: ["March 21", "April 19"],
        polarity: "masculine",
        keywords: ["aggression", "action", "self"],
        ruling_planet_id: [5],
        ruling_house_id: 1,
        strengths: ["brave", "direct", "independent", "deep sense of justice", "natural leader"],
        weaknesses: ["aggressive", "self-centered", "pushy", "inconsistent", "bad-tempered", "selfish"],
        conjunct: "Aries",
        sextile: ["Gemini", "Aquarius"],
        square: ["Cancer", "Capricorn"],
        trine: ["Leo", "Sagittarius"],
        opposite: ["Libra"],
        image: "https://imgur.com/ABsFprk",
        createdAt: new Date(),
        updatedAt: new Date()
      }, {
        sign_name: "Taurus",
        element: "earth",
        modality: "fixed",
        symbol: "the bull",
        dates: ["April 20", "May 20"],
        polarity: "feminine",
        keywords: ["luxury", "pleasure", "money", "value"],
        ruling_planet_id: [4],
        ruling_house_id: 2,
        strengths: ["steady", "driven", "tenacious", "persistent", "trustworthy", "patient"],
        weaknesses: ["materialistic", "resistant to change", "indulgent", "possessive", "stubborn"],
        conjunct: "Taurus",
        sextile: ["Cancer", "Pisces"],
        square: ["Leo", "Aquarius"],
        trine: ["Virgo", "Capricorn"],
        opposite: ["Scorpio"],
        image: "https://imgur.com/jRzNiER",
        createdAt: new Date(),
        updatedAt: new Date()
      }, {
        sign_name: "Gemini",
        element: "air",
        modality: "mutable",
        symbol: "the twins",
        dates: ["May 21", "June 20"],
        polarity: "masculine",
        keywords: ["intelligence", "communication", "language", "learning", "trivial"],
        ruling_planet_id: [3],
        ruling_house_id: 3,
        strengths: ["intelligent", "adaptable", "agile", "communicative", "informative", "connected"],
        weaknesses: ["talkative", "exaggerating", "deceptive", "cunning", "superficial", "inconsistent"],
        conjunct: "Gemini",
        sextile: ["Aries", "Leo"],
        square: ["Virgo", "Pisces"],
        trine: ["Libra", "Aquarius"],
        opposite: ["Sagittarius"],
        image: "https://imgur.com/2i6S6wS",
        createdAt: new Date(),
        updatedAt: new Date()
      }, {
        sign_name: "Cancer",
        element: "water",
        modality: "cardinal",
        symbol: "the crab",
        dates: ["June 21", "July 22"],
        polarity: "feminine",
        keywords: ["mother", "nurture", "emotion", "sensitivity", "intuition"],
        ruling_planet_id: [2],
        ruling_house_id: 4,
        strengths: ["nurturing", "supportive", "healing", "compassionate", "unconditionally loving"],
        weaknesses: ["dependent", "indirect", "moody", "passive aggressive", "unable to let go"],
        conjunct: "Cancer",
        sextile: ["Taurus", "Virgo"],
        square: ["Aries", "Libra"],
        trine: ["Scorpio", "Pisces"],
        opposite: ["Capricorn"],
        image: "https://imgur.com/16BImRw",
        createdAt: new Date(),
        updatedAt: new Date()
      }, {
        sign_name: "Leo",
        element: "fire",
        modality: "fixed",
        symbol: "the lion",
        dates: ["July 23", "August 22"],
        polarity: "masculine",
        keywords: ["ego", "creativity", "self-expression"],
        ruling_planet_id: [1],
        ruling_house_id: 5,
        strengths: ["courageous", "playful", "leader", "fun", "warm", "protective", "generous", "charismatic"],
        weaknesses: ["egotistical", "dominating", "stubborn", "controlling", "ostentacious", "vain"],
        conjunct: "Leo",
        sextile: ["Gemini", "Libra"],
        square: ["Taurus", "Scorpio"],
        trine: ["Aries", "Sagittarius"],
        opposite: ["Aquarius"],
        image: "https://imgur.com/DTArV8t",
        createdAt: new Date(),
        updatedAt: new Date()
      }, {
        sign_name: "Virgo",
        element: "earth",
        modality: "mutable",
        symbol: "the virgin",
        dates: ["August 23", "September 22"],
        polarity: "feminine",
        keywords: ["service", "analytical"],
        ruling_planet_id: [3],
        ruling_house_id: 6,
        strengths: ["modest", "humble", "orderly", "altruistic", "responsible", "organized"],
        weaknesses: ["obsessive", "critical", "excessive attention to detail", "perfectionist"],
        conjunct: "Virgo",
        sextile: ["Cancer", "Scorpio"],
        square: ["Gemini", "Sagittarius"],
        trine: ["Taurus", "Capricorn"],
        opposite: ["Pisces"],
        image: "https://imgur.com/JHeZKby",
        createdAt: new Date(),
        updatedAt: new Date()
      }, {
        sign_name: "Libra",
        element: "air",
        modality: "cardinal",
        symbol: "the scales",
        dates: ["September 23", "October 22"],
        polarity: "masculine",
        keywords: ["beauty", "relationships", "diplomacy", "grace", "balance"],
        ruling_planet_id: [4],
        ruling_house_id: 7,
        strengths: ["charming", "harmonious", "diplomatic", "easy-going nature", "polished"],
        weaknesses: ["indecisive", "superficial", "hypocritical", "gullible", "passive aggressive"],
        conjunct: "Libra",
        sextile: ["Leo", "Sagittarius"],
        square: ["Cancer", "Capricorn"],
        trine: ["Gemini", "Aquarius"],
        opposite: ["Aries"],
        image: "https://imgur.com/xmJvBpJ",
        createdAt: new Date(),
        updatedAt: new Date()
      }, {
        sign_name: "Scorpio",
        element: "water",
        modality: "fixed",
        symbol: "the scorpion",
        dates: ["October 23", "November 22"],
        polarity: "feminine",
        keywords: ["intensity", "power", "intuition", "possession"],
        ruling_planet_id: [10, 5],
        ruling_house_id: 8,
        strengths: ["passionate", "driven", "perceptive", "emotional", "sacrificing", "determined"],
        weaknesses: ["vindictive", "paranoid", "destructive", "possessive", "jealous", "clingy"],
        conjunct: "Scorpio",
        sextile: ["Virgo", "Capricorn"],
        square: ["Leo", "Aquarius"],
        trine: ["Cancer", "Pisces"],
        opposite: ["Taurus"],
        image: "https://imgur.com/xmJRkxN",
        createdAt: new Date(),
        updatedAt: new Date()
      }, {
        sign_name: "Sagittarius",
        element: "fire",
        modality: "mutable",
        symbol: "the archer",
        dates: ["November 23", "December 21"],
        polarity: "masculine",
        keywords: ["optimism", "expansion", "foreign"],
        ruling_planet_id: [6],
        ruling_house_id: 9,
        strengths: ["ambitious", "lucky", "moral", "optimistic", "enthusiastic", "open-minded", "versatile"],
        weaknesses: ["gluttonous", "lazy", "restless", "irresponsible", "blindy optimistic", "tactless"],
        conjunct: "Sagittarius",
        sextile: ["Libra", "Aquarius"],
        square: ["Virgo", "Pisces"],
        trine: ["Aries", "Leo"],
        opposite: ["Gemini"],
        image: "https://imgur.com/Db8YtO2",
        createdAt: new Date(),
        updatedAt: new Date()
      }, {
        sign_name: "Capricorn",
        element: "earth",
        modality: "cardinal",
        symbol: "the goat",
        dates: ["December 22", "January 19"],
        polarity: "feminine",
        keywords: ["ambition"],
        ruling_planet_id: [7],
        ruling_house_id: 10,
        strengths: ["driven", "patient", "strategic", "determined", "disciplined", "responsible", "persistent"],
        weaknesses: ["pessimistic", "greedy", "cynical", "fearful", "ruthless", "rigid", "miserly"],
        conjunct: "Capricorn",
        sextile: ["Scorpio", "Pisces"],
        square: ["Aries", "Libra"],
        trine: ["Taurus", "Virgo"],
        opposite: ["Cancer"],
        image: "https://imgur.com/6aR4Xhm",
        createdAt: new Date(),
        updatedAt: new Date()
      }, {
        sign_name: "Aquarius",
        element: "air",
        modality: "fixed",
        symbol: "the water-bearer",
        dates: ["January 20", "February 18"],
        polarity: "masculine",
        keywords: ["abstract", "intelligence", "different"],
        ruling_planet_id: [8, 7],
        ruling_house_id: 11,
        strengths: ["intelligent", "inventive", "humanistic", "friendly", "altruistic", "reformative"],
        weaknesses: ["emotionally detached", "scatterbrained", "irresponsible", "impersonal", "aloof"],
        conjunct: "Aquarius",
        sextile: ["Aries", "Sagittarius"],
        square: ["Taurus", "Scorpio"],
        trine: ["Gemini", "Libra"],
        opposite: ["Leo"],
        image: "https://imgur.com/zpnjVJ8",
        createdAt: new Date(),
        updatedAt: new Date()
      }, {
        sign_name: "Pisces",
        element: "water",
        modality: "mutable",
        symbol: "the fish",
        dates: ["February 19", "March 20"],
        polarity: "feminine",
        keywords: ["dreams", "escapism", "the arts", "intuition", "compassion", "romance"],
        ruling_planet_id: [9, 6],
        ruling_house_id: 12,
        strengths: ["mystical", "intuitive", "creative", "romantic", "compassionate", "sensitive"],
        weaknesses: ["escapist", "unrealistic", "submissive", "self-pitying", "dependent", "co-dependent"],
        conjunct: "Pisces",
        sextile: ["Taurus", "Capricorn"],
        square: ["Gemini", "Sagittarius"],
        trine: ["Cancer", "Scorpio"],
        opposite: ["Virgo"],
        image: "https://imgur.com/LYIQJUT",
        createdAt: new Date(),
        updatedAt: new Date()
      }
    ], {});
  },

  down: (queryInterface, Sequelize) => {
      return queryInterface.bulkDelete('Zodiacs', null, {});
  }
};
