'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {
      return queryInterface.bulkInsert('Planets', [{
        planet_name: "Sun",
        represents: ["ego", "core-self"],
        speed: 0.59,
        retrograde: false,
        planet_type: "luminary",
        sign_rule_id: [5],
        house_rule_id: [5],
        favorable: "benefic",
        domicile: ["Leo"],
        detriment: ["Aquarius"],
        exaltation: "Aries",
        fall: "Libra",
        planet_glyph: "https://imgur.com/2wyZxuI",
        createdAt: new Date(),
        updatedAt: new Date()
      }, {
        planet_name: "Moon",
        represents: ["STRING"],
        speed: 12.30,
        retrograde: false,
        planet_type: "luminary",
        sign_rule_id: [4],
        house_rule_id: [4],
        favorable: "benefic",
        domicile: ["STRING"],
        detriment: ["STRING"],
        exaltation: "Taurus",
        fall: "Scorpio",
        planet_glyph: "https://imgur.com/u3BkhVl",
        createdAt: new Date(),
        updatedAt: new Date()
      }, {
        planet_name: "Mercury",
        represents: ["STRING"],
        speed: 1.05,
        retrograde: true,
        planet_type: "personal",
        sign_rule_id: [3, 6],
        house_rule_id: [3, 6],
        favorable: "neutral",
        domicile: ["Gemini", "Virgo"],
        detriment: ["Sagittarius", "Pisces"],
        exaltation: "Virgo",
        fall: "Pisces",
        planet_glyph: "https://imgur.com/PNwx7BH",
        createdAt: new Date(),
        updatedAt: new Date()
      }, {
        planet_name: "Venus",
        represents: ["STRING"],
        speed: 1.10,
        retrograde: true,
        planet_type: "personal",
        sign_rule_id: [2, 7],
        house_rule_id: [2, 7],
        favorable: "benefic",
        domicile: ["Taurus", "Libra"],
        detriment: ["Scorpio", "Aries"],
        exaltation: "Pisces",
        fall: "Virgo",
        planet_glyph: "https://imgur.com/uU07ZHG",
        createdAt: new Date(),
        updatedAt: new Date()
      }, {
        planet_name: "Mars",
        represents: ["STRING"],
        speed: 0.37,
        retrograde: true,
        planet_type: "personal",
        sign_rule_id: [1, 8],
        house_rule_id: [1],
        favorable: "malefic",
        domicile: ["Aries", "Scorpio"],
        detriment: ["Libra", "Taurus"],
        exaltation: "Capricorn",
        fall: "Cancer",
        planet_glyph: "https://imgur.com/HRdipJU",
        createdAt: new Date(),
        updatedAt: new Date()
      }, {
        planet_name: "Jupiter",
        represents: ["STRING"],
        speed: 0.05,
        retrograde: true,
        planet_type: "social",
        sign_rule_id: [9, 12],
        house_rule_id: [9],
        favorable: "benefic",
        domicile: ["Sagittarius", "Pisces"],
        detriment: ["Gemini", "Virgo"],
        exaltation: "Cancer",
        fall: "Capricorn",
        planet_glyph: "https://imgur.com/kRHAvcn",
        createdAt: new Date(),
        updatedAt: new Date()
      }, {
        planet_name: "Saturn",
        represents: ["STRING"],
        speed: 0.02,
        retrograde: true,
        planet_type: "social",
        sign_rule_id: [10, 11],
        house_rule_id: [10],
        favorable: "malefic",
        domicile: ["Capricorn", "Aquarius"],
        detriment: ["Cancer", "Leo"],
        exaltation: "Libra",
        fall: "Aries",
        planet_glyph: "https://imgur.com/FUyraRJ",
        createdAt: new Date(),
        updatedAt: new Date()
      }, {
        planet_name: "Uranus",
        represents: ["STRING"],
        speed: 0.0042,
        retrograde: true,
        planet_type: "generational",
        sign_rule_id: [11],
        house_rule_id: [11],
        favorable: "malefic",
        domicile: ["Aquarius"],
        detriment: ["Leo"],
        exaltation: "Scorpio",
        fall: "Taurus",
        planet_glyph: "https://imgur.com/q7BanD1",
        createdAt: new Date(),
        updatedAt: new Date()
      }, {
        planet_name: "Neptune",
        represents: ["STRING"],
        speed: 0.0024,
        retrograde: true,
        planet_type: "generational",
        sign_rule_id: [12],
        house_rule_id: [12],
        favorable: "malefic",
        domicile: ["Pisces"],
        detriment: ["Virgo"],
        exaltation: "Cancer",
        fall: "Capricorn",
        planet_glyph: "https://imgur.com/BMkWsHZ",
        createdAt: new Date(),
        updatedAt: new Date()
      }, {
        planet_name: "Pluto",
        represents: ["STRING"],
        speed: 0.0015,
        retrograde: true,
        planet_type: "generational",
        sign_rule_id: [8],
        house_rule_id: [8],
        favorable: "malefic",
        domicile: ["Scorpio"],
        detriment: ["Taurus"],
        exaltation: "Aries",
        fall: "Libra",
        planet_glyph: "https://imgur.com/ga3mEY1",
        createdAt: new Date(),
        updatedAt: new Date()
      }, {
        planet_name: "Chiron",
        represents: ["STRING"],
        speed: 0.02,
        retrograde: true,
        planet_type: "asteroid",
        sign_rule_id: [2, 6],
        house_rule_id: [null],
        favorable: "neutral",
        domicile: ["Taurus", "Virgo"],
        detriment: ["Scorpio", "Pisces"],
        exaltation: "Sagittarius",
        fall: "Gemini",
        planet_glyph: "https://imgur.com/O32D3NC",
        createdAt: new Date(),
        updatedAt: new Date()
      }, {
        planet_name: "North Node",
        represents: ["STRING"],
        speed: 0.0015,
        retrograde: true,
        planet_type: "lunar node",
        sign_rule_id: [null],
        house_rule_id: [null],
        favorable: "neutral",
        domicile: ["n/a"],
        detriment: ["n/a"],
        exaltation: "n/a",
        fall: "n/a",
        planet_glyph: "https://imgur.com/xeXcwZ7",
        createdAt: new Date(),
        updatedAt: new Date()
      }, {
        planet_name: "South Node",
        represents: ["STRING"],
        speed: 0.0015,
        retrograde: true,
        planet_type: "lunar node",
        sign_rule_id: [null],
        house_rule_id: [null],
        favorable: "neutral",
        domicile: ["n/a"],
        detriment: ["n/a"],
        exaltation: "n/a",
        fall: "n/a",
        planet_glyph: "https://imgur.com/61VSMo1",
        createdAt: new Date(),
        updatedAt: new Date()
      }, {
        planet_name: "Ceres",
        represents: ["STRING"],
        speed: 0.12,
        retrograde: true,
        planet_type: "asteroid",
        sign_rule_id: [2, 6],
        house_rule_id: [null],
        favorable: "neutral",
        domicile: ["Taurus", "Virgo"],
        detriment: ["Scorpio", "Pisces"],
        exaltation: "Gemini",
        fall: "Sagittarius",
        planet_glyph: "https://imgur.com/kCXF53R",
        createdAt: new Date(),
        updatedAt: new Date()
      }, {
        planet_name: "Pallas Athene",
        represents: ["STRING"],
        speed: 0.12,
        retrograde: true,
        planet_type: "asteroid",
        sign_rule_id: [null],
        house_rule_id: [null],
        favorable: "neutral",
        domicile: ["n/a"],
        detriment: ["n/a"],
        exaltation: "n/a",
        fall: "n/a",
        planet_glyph: "https://imgur.com/xuEeB9P",
        createdAt: new Date(),
        updatedAt: new Date()
      }, {
        planet_name: "Juno",
        represents: ["STRING"],
        speed: 0.14,
        retrograde: true,
        planet_type: "asteroid",
        sign_rule_id: [null],
        house_rule_id: [null],
        favorable: "neutral",
        domicile: ["n/a"],
        detriment: ["n/a"],
        exaltation: "n/a",
        fall: "n/a",
        planet_glyph: "https://imgur.com/BmDJcCh",
        createdAt: new Date(),
        updatedAt: new Date()
      }, {
        planet_name: "Vesta",
        represents: ["STRING"],
        speed: 0.16,
        retrograde: true,
        planet_type: "asteroid",
        sign_rule_id: [null],
        house_rule_id: [null],
        favorable: "neutral",
        domicile: ["n/a"],
        detriment: ["n/a"],
        exaltation: "n/a",
        fall: "n/a",
        planet_glyph: "https://imgur.com/tqaeJmI",
        createdAt: new Date(),
        updatedAt: new Date()
      }, {
        planet_name: "Ascendant",
        represents: ["STRING"],
        speed: null,
        retrograde: false,
        planet_type: "angular point",
        sign_rule_id: [1],
        house_rule_id: [1],
        favorable: "neutral",
        domicile: ["n/a"],
        detriment: ["n/a"],
        exaltation: "n/a",
        fall: "n/a",
        planet_glyph: "https://imgur.com/tqaeJmI",
        createdAt: new Date(),
        updatedAt: new Date()
      } , {
        planet_name: "Midheaven",
        represents: ["STRING"],
        speed: null,
        retrograde: false,
        planet_type: "angular point",
        sign_rule_id: [10],
        house_rule_id: [10],
        favorable: "neutral",
        domicile: ["n/a"],
        detriment: ["n/a"],
        exaltation: "n/a",
        fall: "n/a",
        planet_glyph: "https://imgur.com/tqaeJmI",
        createdAt: new Date(),
        updatedAt: new Date()
      }
    ], {});
  },

  down: (queryInterface, Sequelize) => {
      return queryInterface.bulkDelete('Planets', null, {});
  }
};
